"""
Query Planner (QP) — Stage 2 of the Rufus pipeline.

Mirrors Amazon Rufus's critical-path blocker: a specialized classifier that
runs FIRST and determines the retrieval + reasoning strategy before any
product data is fetched or tokens are generated by the main LLM.

Implementation: KEYWORD-BASED (no LLM call).
Rationale: An extra Gemini call per request exhausts the free-tier 5 RPM quota.
Keyword matching is faster, uses zero API quota, and is accurate enough for
routing purposes. This mirrors how Rufus's custom small model works — it's a
fast, trained classifier, not a frontier LLM.

Query types and downstream implications:
  factual    → simple spec lookup → shallow RAG, one paragraph answer
  comparison → best-of / vs queries → full RAG + competitor emphasis + table output
  planning   → multi-step / trip planning → full RAG + structured recommendations
  agentic    → follow-up action → actionable framing

Routing config per type determines:
  - rag_top_k: how many RAG chunks to retrieve
  - require_competitors: whether to force competitor inclusion
  - output_emphasis: directive appended to the system prompt
"""
from __future__ import annotations

import logging
import re
from typing import Literal

logger = logging.getLogger(__name__)

QueryType = Literal["factual", "comparison", "planning", "agentic"]

# Routing config per query type
QUERY_ROUTING: dict[QueryType, dict] = {
    "factual": {
        "rag_top_k": 5,
        "require_competitors": False,
        "output_emphasis": "Direct, concise spec answer. One paragraph max. Cite the exact spec from the listing.",
        "model_note": "Simple lookup — minimal context needed.",
    },
    "comparison": {
        "rag_top_k": 15,
        "require_competitors": True,
        "output_emphasis": "Head-to-Head Comparison Table (markdown) REQUIRED. Show top 3-4 differentiating specs. Clearly state which product wins for the shopper's use case.",
        "model_note": "Feature differentiation — competitor data critical.",
    },
    "planning": {
        "rag_top_k": 15,
        "require_competitors": True,
        "output_emphasis": "Structured recommendation with clear use-case fit analysis. Address all user constraints explicitly (budget, region, specific needs). Provide a final verdict.",
        "model_note": "Multi-step reasoning — user has complex requirements.",
    },
    "agentic": {
        "rag_top_k": 10,
        "require_competitors": True,
        "output_emphasis": "Actionable recommendation. Clearly state what the user should DO next. Be direct.",
        "model_note": "Follow-up intent — user has prior context.",
    },
}

# ── Keyword patterns per query type (order matters: more specific first) ──────

_AGENTIC_PATTERNS = re.compile(
    r"\b(add to cart|buy now|order|purchase this|get this|take this|go with|should i get|which one should)\b",
    re.IGNORECASE,
)

_PLANNING_PATTERNS = re.compile(
    r"\b(plan|planning|trip|setup|kit|checklist|guide|complete (list|set|guide)|what do i need|prepare|organise|organize|full setup)\b",
    re.IGNORECASE,
)

_COMPARISON_PATTERNS = re.compile(
    r"\b(best|vs\.?|versus|compare|comparison|difference between|which is better|recommend|top \d+|under \d+|within budget|alternatives?|options?|suggest|cheapest|most affordable)\b",
    re.IGNORECASE,
)

_FACTUAL_PATTERNS = re.compile(
    r"\b(watt(age)?|weight|dimension|size|color|material|compatible|does it|is it|can it|capacity|voltage|warranty|certificate|certif|spec(ification)?|how many|what is the)\b",
    re.IGNORECASE,
)


def classify_query_sync(query: str) -> tuple[QueryType, dict]:
    """
    Pure keyword-based query classifier. No LLM call. Runs in <1ms.
    Returns (query_type, routing_config).
    """
    q = query.strip()

    if _AGENTIC_PATTERNS.search(q):
        qt: QueryType = "agentic"
    elif _PLANNING_PATTERNS.search(q):
        qt = "planning"
    elif _COMPARISON_PATTERNS.search(q):
        qt = "comparison"
    elif _FACTUAL_PATTERNS.search(q):
        qt = "factual"
    else:
        # Default: comparison is the safest fallback (includes competitor data)
        qt = "comparison"

    routing = QUERY_ROUTING[qt]
    logger.info(f"QP (keyword): '{qt}' | RAG top-k={routing['rag_top_k']}")
    return qt, routing


async def classify_query(query: str) -> tuple[QueryType, dict]:
    """
    Async wrapper for classify_query_sync.
    Kept async so the router can use asyncio.gather() without changes.
    """
    return classify_query_sync(query)
